site_name: Medicare CMS Documentation
site_description: 'Aggregated Medicare documentation in a single place'
site_author: 'DiscWeb'
site_url: 'https://discweb.github.io/disc_web/'

docs_dir: 'docs'
site_dir: 'site'

repo_name: 'disc_web'
repo_url: 'https://github.com/DiscWeb/disc_web.git'
#edit_uri: 'blob/master/docs/'
nav:
    - Home: 'index.md'
    - A:
        - Overview: 'A/overview.md'
    - B:
        - Title B: 'B/b.md'

theme:
    feature:
        tabs: true
    logo:
        icon: 'local_library'
    name: 'material'
    language: 'en'
    palette:
        primary: 'blue'
        accent:  'light blue'
    font:
        text: 'Nunito Sans'
        code: 'Fira Code'

extra_javascript:
    - js/helpers.js
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML'

markdown_extensions:
    - admonition
    - attr_list
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - pymdownx.arithmatex
    - pymdownx.betterem
    - pymdownx.caret:
        insert: false
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.escapeall:
        hardbreak: true
        nbsp: true
    - pymdownx.magiclink:
        hide_protocol: true
        repo_url_shortener: true
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde
    - toc:
        permalink: true
        