site_name: Medicare CMS Documentation
site_description: 'Aggregated Medicare documentation in a single place'
site_author: 'DiscWeb'
site_url: 'https://discweb.github.io/disc_web/'

docs_dir: 'docs'
site_dir: 'site'

repo_name: 'disc_web'
repo_url: 'https://github.com/DiscWeb/disc_web.git'
#edit_uri: 'blob/master/docs/'
nav:
    - Home: 'index.md'
    - A:
        - Overview: 'A/overview.md'
    - B:
        - Title B: 'B/b.md'

theme:
    feature:
        tabs: true
    logo:
        icon: 'local_library'
    name: 'material'
    language: 'en'
    palette:
        primary: 'blue'
        accent:  'light blue'
    font:
        text: 'Nunito Sans'
        code: 'Fira Code'